apiVersion: jenkins.io/v1alpha2
kind: Pipeline
metadata:
  name: hello-grpc
  namespace: jenkins
spec:
  type: pipeline
  pipeline:
    agent:
      any: true
    stages:
      - name: Checkout
        steps:
          - checkout: scm
      - name: Build
        steps:
          - sh: docker build -t hello-grpc:${BUILD_NUMBER} .
      - name: Test
        steps:
          - sh: |
              docker run -d --name test-container hello-grpc:${BUILD_NUMBER}
              sleep 10
              docker ps | grep test-container
              docker rm -f test-container
      - name: Push
        steps:
          - script: |
              # Add your Docker registry credentials here if needed
              # docker.withRegistry('https://your-registry', 'docker-credentials') {
              #     docker.image("hello-grpc:${BUILD_NUMBER}").push()
              # }
    post:
      always:
        - cleanWs: {}
      success:
        - echo: 'Pipeline completed successfully!'
      failure:
        - echo: 'Pipeline failed!'
  source:
    git:
      url: https://github.com/khushal1198/hello_grpc.git
      branch: master
      credentials: github-credentials 