version: '3.8'

services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    ports:
      - "50051:50051"
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; grpc.insecure_channel('localhost:50051').connect()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hello-grpc-network

  ui-server:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8081:8081"
    environment:
      - PYTHONPATH=/app
      - GRPC_SERVER_HOST=grpc-server
      - GRPC_SERVER_PORT=50051
      - UI_SERVER_PORT=8081
    depends_on:
      grpc-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hello-grpc-network

networks:
  hello-grpc-network:
    driver: bridge 