# User Service - Development Environment Configuration

database:
  host: "shivi.local"
  port: 32543
  user: "test_user"
  password: "test123"
  database: "myapp"
  schema: "test"
  pool:
    size: 15
    max_overflow: 3
    timeout: 30

jwt:
  secret_key: "dev-secret-key-change-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7 