name: Build and Push Docker Images

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MANIFESTS_REPO: khushal1198/khushal-k8s-manifests

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for gRPC server
      id: meta-grpc
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-grpc
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Extract metadata for UI server
      id: meta-ui
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push gRPC server image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.grpc
        push: true
        tags: ${{ steps.meta-grpc.outputs.tags }}
        labels: ${{ steps.meta-grpc.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push UI server image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.ui
        push: true
        tags: ${{ steps.meta-ui.outputs.tags }}
        labels: ${{ steps.meta-ui.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Clone manifests repository
      run: |
        git clone https://x-access-token:${{ secrets.MANIFESTS_REPO_TOKEN }}@github.com/${{ env.MANIFESTS_REPO }}.git manifests-repo
        cd manifests-repo

    - name: Update deployment manifests
      run: |
        cd manifests-repo
        # Get the SHA tags from the metadata action outputs
        GRPC_SHA_TAG=$(echo "${{ steps.meta-grpc.outputs.tags }}" | grep -o "master-[a-f0-9]*" | head -1)
        UI_SHA_TAG=$(echo "${{ steps.meta-ui.outputs.tags }}" | grep -o "master-[a-f0-9]*" | head -1)
        
        if [ -z "$GRPC_SHA_TAG" ] || [ -z "$UI_SHA_TAG" ]; then
          echo "Error: Could not find SHA tags in metadata output"
          exit 1
        fi
        
        echo "Updating gRPC deployment with tag: ${GRPC_SHA_TAG}"
        echo "Updating UI deployment with tag: ${UI_SHA_TAG}"
        
        # Update gRPC server deployment
        sed -i "s|image: ghcr.io/khushal1198/hello_grpc-grpc:.*|image: ghcr.io/khushal1198/hello_grpc-grpc:${GRPC_SHA_TAG}|" hello-grpc/grpc-deployment.yaml
        
        # Update UI server deployment
        sed -i "s|image: ghcr.io/khushal1198/hello_grpc-ui:.*|image: ghcr.io/khushal1198/hello_grpc-ui:${UI_SHA_TAG}|" hello-grpc/ui-deployment.yaml
        
        echo "Updated deployment manifests with tags: gRPC=${GRPC_SHA_TAG}, UI=${UI_SHA_TAG}"

    - name: Commit and push to manifests repository
      run: |
        cd manifests-repo
        GRPC_SHA_TAG=$(echo "${{ steps.meta-grpc.outputs.tags }}" | grep -o "master-[a-f0-9]*" | head -1)
        UI_SHA_TAG=$(echo "${{ steps.meta-ui.outputs.tags }}" | grep -o "master-[a-f0-9]*" | head -1)
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add hello-grpc/grpc-deployment.yaml hello-grpc/ui-deployment.yaml
        git commit -m "Auto-update hello-grpc deployments: gRPC=${GRPC_SHA_TAG}, UI=${UI_SHA_TAG}" || exit 0
        git push origin main 