name: Build and Push Docker Image

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MANIFESTS_REPO: khushal1198/khushal-k8s-manifests

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Clone manifests repository
      run: |
        git clone https://x-access-token:${{ secrets.MANIFESTS_REPO_TOKEN }}@github.com/${{ env.MANIFESTS_REPO }}.git manifests-repo
        cd manifests-repo

    - name: Update deployment manifest
      run: |
        cd manifests-repo
        # Get the SHA tag from the metadata action output
        SHA_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep -o "master-[a-f0-9]*" | head -1)
        if [ -z "$SHA_TAG" ]; then
          echo "Error: Could not find SHA tag in metadata output"
          exit 1
        fi
        echo "Updating deployment with tag: ${SHA_TAG}"
        sed -i "s|image: ghcr.io/khushal1198/hello_grpc:.*|image: ghcr.io/khushal1198/hello_grpc:${SHA_TAG}|" hello-grpc/deployment.yaml
        echo "Updated deployment.yaml with tag: ${SHA_TAG}"

    - name: Commit and push to manifests repository
      run: |
        cd manifests-repo
        SHA_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep -o "master-[a-f0-9]*" | head -1)
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add hello-grpc/deployment.yaml
        git commit -m "Auto-update hello-grpc deployment with tag ${SHA_TAG}" || exit 0
        git push origin main 